### ISSUE TITLE
Build Job Class

### ISSUE THREAD

**Issue by Ivyqiuhan** [Ivyqiuhan/CS-Students-Job-Searching-App#10]
- think about other job website, for the common fields.
- do some research on update fields after being load to database

**Comment by Ivyqiuhan** [comment]
Careerjet API
https://www.careerjet.com/partners/api/java/

**Comment by Ivyqiuhan** [comment]
monster:
http://partner.monster.com/apply-with-monster-implementing

**Comment by Ivyqiuhan** [comment]
Lever Postings
https://github.com/lever/postings-api/blob/master/README.md#get-a-list-of-job-postings

**Comment by netapp-andrea3** [comment]
look for common fields
